/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://feflmzuimra4ngnhvkl7xmdge4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-v5ot7tjntbeflhq5hvaski5mdy",
    "aws_cognito_identity_pool_id": "us-east-2:8a1547aa-9fc3-4748-8620-fbd1d72f5be7",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_rT8a1IxAb",
    "aws_user_pools_web_client_id": "5mj3b5s8ijgsnp9kuulmcaoicv",
    "oauth": {},
    "aws_content_delivery_bucket": "hydratehomieredone-20200901114008-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://hydratehomieredone-20200901114008-hostingbucket-dev.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
